ignoreMouseEventsShortcut: "CommandOrControl+Shift+X"
quitShortcut: "CommandOrControl+Shift+Q"
overlay:
  font: "Consolas"
  color: "green"
  size: "medium"
  text: "[%time%] CPU:%cpu%/RAM:%ram%/GPU:%gpu%"